FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g ts-node typescript

COPY prisma ./prisma
RUN npm run prisma:generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/app.js"]